driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-7
  - name: debian-8.9
  - name: fedora-26
  - name: freebsd-10
  - name: freebsd-11
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion
  - name: opensuse-13.2
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-chef-12.5
    driver_config:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12.5.1

suites:
  - name: default
    data_bags_path: "./test/fixtures/data_bags"
    run_list:
      - recipe[users_test::default]
